platform :ios, '9.0'

use_frameworks!
inhibit_all_warnings!

def shared_pods
  pod 'FolioReaderKit', path: '../'
end

def testing_pods
  pod 'Quick', '~> 3.0'
  pod 'Nimble', '~> 8.0' 
end

target 'Example' do
  shared_pods
end

target 'Storyboard-Example' do
	shared_pods
end

target 'MultipleInstance-Example' do
    shared_pods
end

target 'FolioReaderTests' do
  shared_pods
  testing_pods
end
